<a href="https://colab.research.google.com/github/jomonthomaslobo/mlstudy/blob/master/kerastensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensorflow

In [1]:
import tensorflow as tf
node1=tf.constant(10)
node2=tf.constant(20)
node3=tf.add(node1,node2)#add two nodes
print(node3)

tf.Tensor(30, shape=(), dtype=int32)


KERAS

In [6]:
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
img=load_img('/content/photo-of-red-rose-1820567.jpg')
print(type(img))
print(img.format)
print(img.mode)
print(img.size)
array=img_to_array(img)#array_to_image also there
print(array)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
JPEG
RGB
(2124, 3186)
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
